name: learn-github-actions

run-name: ${{github.actor}} is learning github actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "hello world"
        shell: bash

  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: good bye
        run: echo "good bye"
        shell: bash

  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "14"

      - run: npm install -g bats
      - run: bats -v
